//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyekAkhir_Teknet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporanPasien2
    {
        public int id_laporan { get; set; }
        public string Gejala { get; set; }
        public int Jumlah_Pasien { get; set; }
        public string Deskripsi { get; set; }
    }
}
