//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyekAkhir_Teknet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterVaksin2
    {
        public int id_daftar { get; set; }
        public string nama { get; set; }
        public string jenis_kelamin { get; set; }
        public string no_hp { get; set; }
        public string alamat { get; set; }
    }
}
