//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyekAkhir_Teknet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TambahVaksin
    {
        public int No_Vaksin { get; set; }
        public string Jenis_Vaksin { get; set; }
        public string Gejala_Yang_Cocok { get; set; }
        public int Jumlah_Produksi { get; set; }
    }
}
