//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyekAkhir_Teknet
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporanPasien
    {
        public string Deskripsi_Laporan { get; set; }
        public string Gejala_Pasien { get; set; }
        public int Jumlah_Pasien { get; set; }
    }
}
